import './globals.css';

import type { Metadata } from 'next';

import { MantineProvider } from '@mantine/core';
import '@mantine/core/styles.css';

import { Header } from '@/components/header';
import { Sidebar } from '@/components/sidebar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <MantineProvider>
          <Header />
          <main className="flex h-full overflow-auto flex-1">
            <Sidebar />
            {children}
          </main>
        </MantineProvider>
      </body>
    </html>
  );
}
